# Generated by Django 3.2.3 on 2023-05-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0044_auto_20230503_1400'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Oprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Datum zadání')),
                ('placement', models.CharField(max_length=128, verbose_name='Umístění')),
                ('description', models.CharField(max_length=128, verbose_name='Popis závady')),
                ('replacement_parts', models.CharField(blank=True, max_length=128, null=True, verbose_name='Náhradní díly')),
                ('est_finish_date', models.DateField(blank=True, null=True, verbose_name='Předpokládané datum opravy')),
                ('person_assigned', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kdo řeší')),
                ('scope', models.CharField(blank=True, max_length=128, null=True, verbose_name='Rozsah práce')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Datum dokončení')),
                ('note', models.CharField(blank=True, max_length=128, null=True, verbose_name='Poznámka')),
                ('done', models.BooleanField(default=False, verbose_name='Hotovo')),
                ('work_estimated', models.CharField(blank=True, max_length=128, null=True, verbose_name='Odhad práce')),
            ],
            options={
                'verbose_name': 'Oprava',
                'verbose_name_plural': 'Opravy',
                'db_table': 'maintenance_Oprava',
            },
        ),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]

