# Generated by Django 3.2.3 on 2023-05-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oprava',
            table=None,
        ),
    ]
