# Generated by Django 3.2.3 on 2021-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoblovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakaznik', models.CharField(blank=True, max_length=128, verbose_name='Zákazník')),
                ('skladovy_material', models.CharField(blank=True, max_length=128, verbose_name='Skladový materiál')),
                ('pozadovany_rozmer', models.CharField(blank=True, max_length=128, verbose_name='Požadovaný rozměr')),
                ('pozadovana_delka', models.CharField(blank=True, max_length=128, verbose_name='Požadovaná délka')),
                ('poznamka', models.CharField(blank=True, max_length=128, verbose_name='Poznámka')),
                ('ks', models.IntegerField(default=1, verbose_name='Kusů')),
                ('ks_hotovo', models.IntegerField(default=0, verbose_name='Kusů hotovo')),
                ('kvalita', models.CharField(blank=True, max_length=128)),
                ('baleni', models.CharField(blank=True, max_length=128, verbose_name='Balení')),
                ('impregnace', models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128)),
                ('kapovani', models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128, verbose_name='Kapování')),
                ('misto_hoblovani', models.CharField(blank=True, max_length=128)),
                ('pozadovane_datum_vyroby', models.DateField(blank=True, verbose_name='Požadované datum výroby')),
                ('hotovo', models.BooleanField(default=False, verbose_name='Hotovo')),
                ('kontrola', models.BooleanField(default=False, verbose_name='Kontrola')),
                ('get_material', models.BooleanField(default=False, verbose_name='Materiál')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
            ],
            options={
                'verbose_name': 'Hoblování',
                'verbose_name_plural': 'Hoblování',
            },
        ),
        migrations.CreateModel(
            name='Rozmitacka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakaznik', models.CharField(blank=True, max_length=128, verbose_name='Zákazník')),
                ('material', models.CharField(blank=True, max_length=128, verbose_name='Materiál')),
                ('umisteni_materialu', models.CharField(blank=True, max_length=128, verbose_name='Umístění materiálu')),
                ('pozadovany_rozmer', models.CharField(blank=True, max_length=128, verbose_name='Požadovaný rozměr')),
                ('pozadovana_delka', models.CharField(blank=True, max_length=128, verbose_name='Požadovaná délka')),
                ('poznamka', models.CharField(blank=True, max_length=128, verbose_name='Poznámka')),
                ('ks', models.IntegerField(default=1, verbose_name='Kusů')),
                ('ks_hotovo', models.IntegerField(default=0, verbose_name='Kusů hotovo')),
                ('kvalita', models.CharField(blank=True, max_length=128)),
                ('baleni', models.CharField(blank=True, max_length=128, verbose_name='Balení')),
                ('impregnace', models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128)),
                ('kapovani', models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128, verbose_name='Kapování')),
                ('pozadovane_datum_vyroby', models.DateField(blank=True, verbose_name='Požadované datum výroby')),
                ('hotovo', models.BooleanField(default=False, verbose_name='Hotovo')),
                ('kontrola', models.BooleanField(default=False, verbose_name='Kontrola')),
                ('get_material', models.BooleanField(default=False, verbose_name='Materiál')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
            ],
            options={
                'verbose_name': 'Rozmítačka',
                'verbose_name_plural': 'Rozmítačka',
            },
        ),
    ]
