# Generated by Django 3.2.3 on 2021-11-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='get_zbytek',
            field=models.BooleanField(default=False, verbose_name='Zbytek'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='get_zbytek',
            field=models.BooleanField(default=False, verbose_name='Zbytek'),
        ),
    ]
