# Generated by Django 3.2.3 on 2021-11-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211116_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='get_zbytek',
            field=models.BooleanField(default=False, verbose_name='Odvoz'),
        ),
    ]
