# Generated by Django 3.2.3 on 2021-06-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_u_materialu_rozmitacka_us_materialu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rozmitacka',
            old_name='p_delka',
            new_name='pozadovana_delka',
        ),
        migrations.RenameField(
            model_name='rozmitacka',
            old_name='date_due',
            new_name='pozadovane_datum_vyroby',
        ),
        migrations.RenameField(
            model_name='rozmitacka',
            old_name='p_rozmer',
            new_name='pozadovany_rozmer',
        ),
        migrations.RenameField(
            model_name='rozmitacka',
            old_name='us_materialu',
            new_name='umisteni_materialu',
        ),
    ]
