# Generated by Django 3.2.3 on 2021-12-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211201_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoblovani',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='rozmitacka',
            name='modified_date',
        ),
    ]
