# Generated by Django 3.2.3 on 2021-12-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211201_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovane_datum_vyroby',
            field=models.DateField(auto_now_add=True, verbose_name='Požadované datum výroby'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovane_datum_vyroby',
            field=models.DateField(auto_now_add=True, verbose_name='Požadované datum výroby'),
        ),
    ]
