# Generated by Django 3.2.3 on 2021-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210610_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozmitacka',
            name='ks',
            field=models.IntegerField(default=1),
        ),
    ]
