# Generated by Django 3.2.3 on 2022-01-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211213_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='priority',
            field=models.IntegerField(default=10, verbose_name='Priorita'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='priority',
            field=models.IntegerField(default=10, verbose_name='Priorita'),
        ),
    ]
