# Generated by Django 3.2.3 on 2021-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_rozmitacka_ks'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozmitacka',
            name='hotovo',
            field=models.BooleanField(default=False),
        ),
    ]
