# Generated by Django 3.2.3 on 2021-12-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211213_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='odpad',
            field=models.BooleanField(default=False, verbose_name='Odpad'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='odpad',
            field=models.BooleanField(default=False, verbose_name='Odpad'),
        ),
    ]
