# Generated by Django 3.2.3 on 2021-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rozmitacka_hotovo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozmitacka',
            name='kontrola',
            field=models.BooleanField(default=False),
        ),
    ]
