# Generated by Django 3.2.3 on 2022-01-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211217_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='impregnace',
            field=models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], default='Ano', max_length=128),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='kapovani',
            field=models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], default='Ano', max_length=128, verbose_name='Kapování'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='impregnace',
            field=models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], default='Ano', max_length=128),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='kapovani',
            field=models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], default='Ano', max_length=128, verbose_name='Kapování'),
        ),
    ]
