# Generated by Django 3.2.3 on 2022-01-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220108_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoblovani',
            options={'ordering': ['priority', '-vytvoreno'], 'verbose_name': 'Hoblování', 'verbose_name_plural': 'Hoblování'},
        ),
        migrations.AlterModelOptions(
            name='rozmitacka',
            options={'ordering': ['priority', '-vytvoreno'], 'verbose_name': 'Rozmítačka', 'verbose_name_plural': 'Rozmítačka'},
        ),
    ]
