# Generated by Django 3.2.3 on 2021-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rozmitacka_kontrola'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozmitacka',
            name='ks_hotovo',
            field=models.IntegerField(default=0),
        ),
    ]
