# Generated by Django 3.2.3 on 2022-01-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rozmitacka_odpad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozmitacka',
            name='odpad',
        ),
    ]
