# Generated by Django 2.2.1 on 2021-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rozmitacka_ks_hotovo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozmitacka',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
