# Generated by Django 3.2.3 on 2022-01-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_rozmitacka_odpad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='baleni',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Balení'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='kvalita',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='misto_hoblovani',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovana_delka',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Požadovaná délka'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovany_rozmer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Požadovaný rozměr'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='poznamka',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='skladovy_material',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Skladový materiál'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='zakaznik',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='baleni',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Balení'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='kvalita',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='material',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovana_delka',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Požadovaná délka'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovany_rozmer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Požadovaný rozměr'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='poznamka',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='umisteni_materialu',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Umístění materiálu'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='zakaznik',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Zákazník'),
        ),
    ]
