# Generated by Django 3.2.3 on 2021-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_rozmitacka_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoblovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakaznik', models.CharField(blank=True, max_length=128)),
                ('skladovy_material', models.CharField(blank=True, max_length=128)),
                ('pozadovany_rozmer', models.CharField(blank=True, max_length=128)),
                ('pozadovana_delka', models.CharField(blank=True, max_length=128)),
                ('poznamka', models.CharField(blank=True, max_length=128)),
                ('ks', models.IntegerField(default=1)),
                ('ks_hotovo', models.IntegerField(default=0)),
                ('kvalita', models.CharField(blank=True, max_length=128)),
                ('baleni', models.CharField(blank=True, max_length=128)),
                ('impregnace', models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128)),
                ('kapovani', models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128)),
                ('misto_hoblovani', models.CharField(blank=True, max_length=128)),
                ('pozadovane_datum_vyroby', models.DateField(blank=True)),
                ('hotovo', models.BooleanField(default=False)),
                ('kontrola', models.BooleanField(default=False)),
            ],
        ),
    ]
