# Generated by Django 3.2.3 on 2022-01-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220110_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozmitacka',
            name='odpad',
        ),
    ]
