# Generated by Django 3.2.3 on 2021-08-23 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_hoblovani'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozmitacka',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
