# Generated by Django 3.2.3 on 2022-01-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_rozmitacka_odpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='odpad',
            field=models.BooleanField(default=False, verbose_name='Odpad'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='odpad',
            field=models.BooleanField(default=False, verbose_name='Odpad'),
        ),
    ]
