# Generated by Django 3.2.3 on 2021-08-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rozmitacka_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rozmitacka',
            old_name='created',
            new_name='vytvoreno',
        ),
    ]
