# Generated by Django 3.2.3 on 2021-08-23 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_created_rozmitacka_vytvoreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
