# Generated by Django 3.2.3 on 2021-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_hoblovani_vytvoreno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoblovani',
            options={'verbose_name': 'Hoblování', 'verbose_name_plural': 'Hoblování'},
        ),
        migrations.AlterModelOptions(
            name='rozmitacka',
            options={'verbose_name': 'Rozmítačka', 'verbose_name_plural': 'Rozmítačka'},
        ),
        migrations.AddField(
            model_name='hoblovani',
            name='material',
            field=models.BooleanField(default=False, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='baleni',
            field=models.CharField(blank=True, max_length=128, verbose_name='Balení'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='hotovo',
            field=models.BooleanField(default=False, verbose_name='Hotovo'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='kapovani',
            field=models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128, verbose_name='Kapování'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='kontrola',
            field=models.BooleanField(default=False, verbose_name='Kontrola'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='ks',
            field=models.IntegerField(default=1, verbose_name='Kusů'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='ks_hotovo',
            field=models.IntegerField(default=0, verbose_name='Kusů hotovo'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovana_delka',
            field=models.CharField(blank=True, max_length=128, verbose_name='Požadovaná délka'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovane_datum_vyroby',
            field=models.DateField(blank=True, verbose_name='Požadované datum výroby'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovany_rozmer',
            field=models.CharField(blank=True, max_length=128, verbose_name='Požadovaný rozměr'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='poznamka',
            field=models.CharField(blank=True, max_length=128, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='skladovy_material',
            field=models.CharField(blank=True, max_length=128, verbose_name='Skladový materiál'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='hoblovani',
            name='zakaznik',
            field=models.CharField(blank=True, max_length=128, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='baleni',
            field=models.CharField(blank=True, max_length=128, verbose_name='Balení'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='hotovo',
            field=models.BooleanField(default=False, verbose_name='Hotovo'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='kapovani',
            field=models.CharField(choices=[('Ano', 'Ano'), ('Ne', 'Ne')], max_length=128, verbose_name='Kapování'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='kontrola',
            field=models.BooleanField(default=False, verbose_name='Kontrola'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='ks',
            field=models.IntegerField(default=1, verbose_name='Kusů'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='ks_hotovo',
            field=models.IntegerField(default=0, verbose_name='Kusů hotovo'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='material',
            field=models.BooleanField(default=False, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovana_delka',
            field=models.CharField(blank=True, max_length=128, verbose_name='Požadovaná délka'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovane_datum_vyroby',
            field=models.DateField(blank=True, verbose_name='Požadované datum výroby'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovany_rozmer',
            field=models.CharField(blank=True, max_length=128, verbose_name='Požadovaný rozměr'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='poznamka',
            field=models.CharField(blank=True, max_length=128, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='umisteni_materialu',
            field=models.CharField(blank=True, max_length=128, verbose_name='Umístění materiálu'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='zakaznik',
            field=models.CharField(blank=True, max_length=128, verbose_name='Zákazník'),
        ),
    ]
