# Generated by Django 3.2.3 on 2022-03-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20220331_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
