# Generated by Django 3.2.3 on 2022-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_hoblovani_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
