# Generated by Django 3.2.3 on 2022-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_hoblovani_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='suche',
            field=models.BooleanField(default=False, verbose_name='Suché'),
        ),
        migrations.AddField(
            model_name='hoblovani',
            name='susarna',
            field=models.BooleanField(default=True, verbose_name='Sušárna'),
        ),
    ]
