# Generated by Django 3.2.3 on 2022-04-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20220406_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoblovani',
            name='susarna',
        ),
        migrations.AddField(
            model_name='hoblovani',
            name='do_susarny',
            field=models.BooleanField(default=True, verbose_name='Do sušárny'),
        ),
    ]
