# Generated by Django 3.2.3 on 2022-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_hoblovani_suche'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='imp',
            field=models.BooleanField(default=False, verbose_name='Impregnace'),
        ),
        migrations.AddField(
            model_name='hoblovani',
            name='kap',
            field=models.BooleanField(default=False, verbose_name='Kapování'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='imp',
            field=models.BooleanField(default=False, verbose_name='Impregnace'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='kap',
            field=models.BooleanField(default=False, verbose_name='Kapování'),
        ),
    ]
