# Generated by Django 3.2.3 on 2022-06-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20220604_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoblovani',
            name='impregnace',
        ),
        migrations.RemoveField(
            model_name='hoblovani',
            name='kapovani',
        ),
    ]
