# Generated by Django 3.2.3 on 2022-06-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20220604_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rozmitacka',
            old_name='imp',
            new_name='impregnace',
        ),
        migrations.RenameField(
            model_name='rozmitacka',
            old_name='kap',
            new_name='kapovani',
        ),
    ]
