# Generated by Django 3.2.3 on 2022-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20220604_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovana_delka_jednotky',
            field=models.CharField(blank=True, default='m', max_length=128, verbose_name='Požadovaná délka - jednotky'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovana_delka_jednotky',
            field=models.CharField(blank=True, default='m', max_length=128, verbose_name='Požadovaná délka - jednotky'),
        ),
    ]
