# Generated by Django 3.2.3 on 2022-06-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20220604_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='pozadovana_delka_cislo',
            field=models.FloatField(default=0, verbose_name='Požadovaná délka'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='pozadovana_delka_cislo',
            field=models.FloatField(default=0, verbose_name='Požadovaná délka'),
        ),
    ]
