# Generated by Django 3.2.3 on 2022-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20220606_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='baliky',
            field=models.IntegerField(default=100, verbose_name='Balíky'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='baliky',
            field=models.IntegerField(default=100, verbose_name='Balíky'),
        ),
    ]
