# Generated by Django 3.2.3 on 2022-08-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20220606_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoblovani',
            name='baliky',
            field=models.IntegerField(default=0, verbose_name='Balíky'),
        ),
        migrations.AlterField(
            model_name='rozmitacka',
            name='baliky',
            field=models.IntegerField(default=0, verbose_name='Balíky'),
        ),
    ]
