# Generated by Django 3.2.3 on 2022-08-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20220806_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoblovani',
            name='baliky',
        ),
        migrations.RemoveField(
            model_name='rozmitacka',
            name='baliky',
        ),
        migrations.CreateModel(
            name='Baliky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ks', models.IntegerField(default=0, verbose_name='Kusů')),
                ('done', models.BooleanField(default=False, verbose_name='Hotovo')),
                ('hoblovani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.hoblovani')),
                ('rozmitacka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.rozmitacka')),
            ],
        ),
        migrations.AddConstraint(
            model_name='baliky',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('hoblovani__isnull', True), ('rozmitacka__isnull', False)), models.Q(('hoblovani__isnull', False), ('rozmitacka__isnull', True)), _connector='OR'), name='orders_baliky_hoblovani_nebo_rozmitacka'),
        ),
    ]
