# Generated by Django 3.2.3 on 2022-08-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20220806_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baliky',
            options={'verbose_name': 'Balík', 'verbose_name_plural': 'Balíky'},
        ),
    ]
