# Generated by Django 3.2.3 on 2022-10-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_baliky_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoblovani',
            name='pozadovana_delka',
        ),
        migrations.RemoveField(
            model_name='rozmitacka',
            name='pozadovana_delka',
        ),
    ]
