# Generated by Django 3.2.3 on 2022-12-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20221005_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoblovani',
            name='modrin',
            field=models.BooleanField(default=False, verbose_name='Modřín'),
        ),
        migrations.AddField(
            model_name='rozmitacka',
            name='modrin',
            field=models.BooleanField(default=False, verbose_name='Modřín'),
        ),
    ]
