# Generated by Django 3.2.3 on 2023-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20221206_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoblovani',
            name='ks_hotovo',
        ),
        migrations.RemoveField(
            model_name='rozmitacka',
            name='ks_hotovo',
        ),
    ]
