# Generated by Django 3.2.3 on 2023-04-25 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20230327_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeznamOprav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('placement', models.CharField(max_length=128, verbose_name='Umístění')),
                ('description', models.CharField(max_length=128, verbose_name='Popis')),
                ('replacement_parts', models.CharField(max_length=128, verbose_name='Náhradní díly')),
                ('est_finish_date', models.DateField(blank=True, null=True, verbose_name='Odhadované datum dokončení')),
                ('person_assigned', models.CharField(max_length=128, verbose_name='Přidělená osoba')),
                ('scope', models.CharField(max_length=128, verbose_name='Rozsah')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Datum dokončení')),
                ('note', models.CharField(blank=True, max_length=128, null=True, verbose_name='Poznámka')),
            ],
        ),
    ]
