# Generated by Django 3.2.3 on 2023-04-26 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_seznamoprav'),
    ]

    operations = [
        migrations.AddField(
            model_name='seznamoprav',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Hotovo'),
        ),
        migrations.AddField(
            model_name='seznamoprav',
            name='work_estimated',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Odhad práce'),
        ),
        migrations.AlterField(
            model_name='seznamoprav',
            name='date_added',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum zadání'),
        ),
        migrations.AlterField(
            model_name='seznamoprav',
            name='description',
            field=models.CharField(max_length=128, verbose_name='Popis závady'),
        ),
        migrations.AlterField(
            model_name='seznamoprav',
            name='est_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Předpokládané datum opravy'),
        ),
        migrations.AlterField(
            model_name='seznamoprav',
            name='person_assigned',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Kdo řeší'),
        ),
        migrations.AlterField(
            model_name='seznamoprav',
            name='replacement_parts',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Náhradní díly'),
        ),
        migrations.AlterField(
            model_name='seznamoprav',
            name='scope',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Rozsah práce'),
        ),
    ]
