# Generated by Django 3.2.3 on 2023-04-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20230426_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeznamOprav',
            new_name='Opravy',
        ),
    ]
