# Generated by Django 3.2.3 on 2023-04-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_rename_seznamoprav_opravy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opravy',
            new_name='Oprava',
        ),
    ]
