# Generated by Django 3.2.3 on 2023-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_rename_opravy_oprava'),
    ]

    database_operations = [
            migrations.AlterModelTable("Oprava", "maintenance_Oprava"),
    ]

    state_operations = [
            migrations.DeleteModel("Oprava"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
